# prometheus.yml

global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['localhost:9400']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

