{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "cluster",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(dcgm_gpu_utilization, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dcgm_gpu_utilization) / count(dcgm_gpu_utilization)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dcgm_mem_copy_utilization) / count(dcgm_mem_copy_utilization)"
    }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_utilization{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_mem_copy_utilization{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "Violations",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dcgm_power_violation{instance=~\"$instance\"} + dcgm_thermal_violation{instance=~\"$instance\"} + dcgm_sync_boost_violation{instance=~\"$instance\"} + dcgm_board_limit_violation{instance=~\"$instance\"} + dcgm_reliability_violation{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_temp{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "dcgm_power_usage{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "dcgm_memory_temp{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - gpu{{ gpu }}"
    }
   ]
  },
  {
   "title": "GPU PCIe Throuput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "irate(dcgm_pcie_rx_throughput{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{ instance }} - gpu{{ gpu }} in"
    },
    {
     "expr": "-irate(dcgm_pcie_tx_throughput{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{ instance }} - gpu{{ gpu }} out"
    }
   ]
  }
 ]
}